# Basic operations

In [7]:
import tensorflow as tf
a = tf.constant(1.0, dtype=tf.float32)
b = tf.constant(1.0, shape=[3,4])
c = tf.constant(1.0, shape=[3,4,5])
d = tf.random_normal(shape=[3,4,5])

print (c)
print (d)

Tensor("Const_10:0", shape=(3, 4, 5), dtype=float32)
Tensor("random_normal_2:0", shape=(3, 4, 5), dtype=float32)


In [5]:
import tensorflow as tf

a = tf.constant(1.0, dtype=tf.float32)
b = tf.constant(2.0, dtype=tf.float32)
c = tf.add(a,b)

sess = tf.Session()

print (sess.run(c))

# c = tf.add(a,b)
# c = tf.subtract(a,b)
# c = tf.multiply(a,b)
# c = tf.div(a,b)

3.0


In [12]:
a = tf.placeholder(dtype=tf.float32, shape=None)
b = tf.placeholder(dtype=tf.float32, shape=None)
c = a + b

with tf.Session() as sess:
    feed = {a:1, b:2}
    print (sess.run(c, feed_dict=feed))
    feed = {a:2, b:4.5}
    print (sess.run(c, feed_dict=feed))
    feed = {a:[2,4], b:[5,6]}
    print (sess.run(c, feed_dict=feed))
    feed = {a:[[2,4],[4,5]], b:[[5,6],[10,15.5]]}
    print (sess.run(c, feed_dict=feed))

3.0
6.5
[  7.  10.]
[[  7.   10. ]
 [ 14.   20.5]]


In [13]:
import numpy as np
a = np.random.randn(2,3)
print(a)

[[ 1.23467058 -1.45026221 -1.1729658 ]
 [-1.23717298 -1.32387524 -1.19197423]]


In [14]:
W = tf.Variable(1.0, dtype=tf.float32)
b = tf.Variable(1.0, dtype=tf.float32)
x = tf.placeholder(dtype=tf.float32, shape=[])
linear_model_output = W * x + b

init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)
    feed = {x:5.0}
    sess.run(linear_model_output, feed_dict=feed)

In [35]:
W = tf.Variable(tf.random_normal(shape=[]), dtype=tf.float32)
b = tf.Variable(tf.random_normal(shape=[]), dtype=tf.float32)
x = tf.placeholder(dtype=tf.float32, shape=[])

linear_model_output = W * x + b

init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)
    feed = {x:5.0}
    out = sess.run(linear_model_output, feed_dict=feed)

In [36]:
print (out)

5.54643


# Quiz 0

In [37]:
import tensorflow as tf
import numpy as np

a = tf.placeholder(dtype=tf.float32, shape=[3,4])
b = tf.placeholder(dtype=tf.float32, shape=[4,6])
c = tf.matmul(a,b)

with tf.Session() as sess:
    feed = {a:np.random.randn(3,4), b:np.random.randn(4,6)}
    
    print(sess.run(c, feed_dict=feed))

[[ 0.08505565 -0.58490849  1.83167613 -2.70274448  2.42757177  2.81944656]
 [-6.17005873  1.4808042  -3.16379309 -1.0665251   5.50483131  5.7013278 ]
 [-1.84733009 -1.14232898 -2.47992396 -0.03241412  0.91053033  0.87809598]]
